### PR TITLE
feature/schemas.datapackages.org

### PR DESCRIPTION
**Pull request by pwalsh**
**Don't merge yet**

@vitorbaptista for your review.

I've also configured the proxy to work off the feature branch, so we can play with that while we work towards a merge.

When the DNS picks up, this should work:

* http://schemas.datapackages.org/registry.csv

And so on...

Changes:

* All schemas live under `schemas.datapackages.org`
* Make liberal use of `$ref` for more DRY
* Update `README.md` for more info on contributing to the registry.

### CODE REVIEW

**Comment by pwalsh** [comment]
* I'll see I'll have to fix the handling of `.html`: http://schemas.datapackages.org/index.html
* I'll also do the rebase with `master`.

Additionally, most important thing for me before we merge, is ensuring that the new use of `$ref` is cool with @vitorbaptista and if not, working out the best way forward for that.

**Comment by vitorbaptista** [comment]
As we talked on the other issue, what I'm trying to avoid is to require a HTTP request to use a schema. I was looking for a way to use a relative `$ref`, so if there is (say) a `definitions.json` in the local filesystem, it'll use it. I looked around `jsonschema` and did some tests, but was unable to do it. It seems it's not possible (http://json-schema.org/latest/json-schema-core.html#anchor25).

If that's true, the only other solution I see now is to "compile" the external `$ref`s into the schema. For example, say the schema is defined as:

```json
{
    "definitions_schema": {
        "id": "http://schemas.datapackages.org/definitions.json#"
    },
   "properties": {
        "name": {
            "$ref": "definitions_schema#/define/name"
        }
    }
}
```

When compiled, it would become:
```json
{
    "definitions_schema": {
        "id": "http://schemas.datapackages.org/definitions.json#",
        "define": {
            "name": {
                "title": "Name",
                "type": "string",
                "pattern": "^([a-z0-9._-]+$",
            }
        }
    },
   "properties": {
        "name": {
            "$ref": "definitions_schema#/define/name"
        }
    }
}
```

It shouldn't be hard to implement, although it complicates things. If we don't do that here, it must be done on the `datapackage-registry-*` libraries, which is even worse IMO.

**Comment by pwalsh** [comment]
@vitorbaptista we can easily make these local references - i just did not do that as it broke tests and i wanted to get other eyes on this.

The solution to the problems you describe is rather straightforward IMHO:

1. We use relative paths for `$ref`, which if I understand correctly from the spec can work with URLs and file paths
2. We use the python lib's `RefResolver` class in our registry lib: http://python-jsonschema.readthedocs.org/en/latest/references/ (similar things exist for the javascript lib)
3. We only make as many http request as schemas in the registry + 1 (definitions.json) when we build the local cache, and likewise, if we are doing live http requests, we only do the extra request to definitions on first request, then the lib can work with a local cache (again, from reading docs of Python lib)

Am I missing something?

**Comment by vitorbaptista** [comment]
If you're able to make those `$ref`s local references (actually, relative references), it would solve almost all the problems :+1:

The only remaining issue is that the schema's user needs to have both the schema itself and their dependencies into the local filesystem to use them. What I mean is that if I download just `http://schemas.datapackages.org/data-package.json` and try to use it as:

```json
import json
import jsonschema

schema = json.load(open('data-package.json'))
jsonschema.validate({'foo': 'bar'}, schema)
```

It won't work, because `definitions.json` wasn't downloaded. To solve it, I would have to somehow pass the base path of `data-package.json` to `jsonschema`. Do you know if that's possible?

**Comment by pwalsh** [comment]
@vitorbaptista lots of examples here: https://github.com/Julian/jsonschema/issues/98#issuecomment-17494592

If I make all those refs relative the tests will break, but can you test it out work your code anyway and see if you can get it to work as expected? If it then seems too fidgety, I'll revert back to the inlined definitions and we'll just merge and move on.

**Comment by pwalsh** [comment]
@vitorbaptista did that in https://github.com/dataprotocols/schemas/commit/5ce3aa7e5852c879a8ec1df280e0d908ca9524b4

**Comment by vitorbaptista** [comment]
That should work fine, although the datapackager-registry API will suffer a bit. Right now, we do:

```python
import datapackage_registry

schema = datapackage_registry.Registry.get('tabular')
# ...
```

With this change, we must do:

```python
import datapackage_registry

schema = datapackage_registry.Registry.get('tabular')
base_path = datapackage_registry.Registry.base_path
# ...
```

Not a big issue, specially because I don't think anyone will use the `datapackage_registry` directly, but the `datapackage_validate` or, more commonly, `datapackage`.

I'm OK with these changes as they are now. It would be good to DRY the schemas a little bit by using something like:

```json
{
    "definitions_schema": {
        "id": "http://schemas.datapackages.org/definitions.json#"
    },
   "properties": {
        "name": {
            "$ref": "definitions_schema#/define/name"
        }
    }
}
```

So the "definitions.json" path is defined in a single place, but it's OK either way.

**Comment by pwalsh** [comment]
@vitorbaptista fine. I think that API change in the registry libs is fine - it is hidden in the implementation as as you say the registry is mostly useful as part of the larger suite of libs.

About the `id` addition: I'm not sure from reading specs but I'm worried that will effect the case where we don't want to make http requests, and rather work directly from local cache?

**Comment by vitorbaptista** [comment]
I might be wrong, but I think the `id` change is just a way to DRY the schema a little. The two files (using `id` or not) should be semantically equivalent.

**Comment by pwalsh** [comment]
@vitorbaptista @danfowler 

* I've now merged #36 and master into this PR.
* I've ran the tests for `datapackage-registry-js` against this PR (the tests are not deep)

I'd like to merge this. @vitorbaptista in order for me to merge this, can you please test the py lib against it, and give me a green light (or not).

**Comment by vitorbaptista** [comment]
@pwalsh I've updated the registry (https://github.com/vitorbaptista/datapackage-registry-py/commit/7318a29f5f317107c7f7aa4a96c8aa54f5b0fabe) and validator (https://github.com/vitorbaptista/datapackage-validate-py/commit/739658e5e2d8ae74264c55b43fb494893b79eea0) to work on this.

The only thing that won't work is:

```python
import datapackage_registry

registry = datapackage_registry.Registry('https://github.com/dataprotocols/schemas/blob/master/registry.csv')
schema = registry.get('base')
# This schema has relative paths, but `registry.base_path` only works for local paths, so it won't be possible to resolve the relative paths
```

This problem would never happen when using `datapackage-validate-py`, because it always creates the registry using its default parameters (i.e `datapackage_registry.Registry()`). It shouldn't be too hard to fix it on registry, though, so I can create an issue to do that later.

Apart from that, everything seems fine, so you can go ahead and merge this :+1:

**Comment by pwalsh** [comment]
@vitorbaptista thanks. So, please do one that issue and fix when possible. I'll merge now. It means that within a few mins, we should port any libs or references to the registry to use `schemas.datapackages.org` as the domain.

**Pull request merged**
