### PR TITLE
Add "data" as property of resource inline with spec

### PR DESCRIPTION
**Pull request by danfowler**
See: http://dataprotocols.org/data-packages/#inline-data

### CODE REVIEW

**Comment by vitorbaptista** [comment]
@danfowler If you have a few minutes to spare, could you do the same patch to `tabular-data-package.json`?

**Comment by pwalsh** [comment]
@vitorbaptista @danfowler note that in my working branch here: https://github.com/dataprotocols/schemas/blob/feature/schemas.datapackages.org/definitions.json I'm making extensive use of `$ref` and refactoring all the packages so that they reference the same basic definitions: https://github.com/dataprotocols/schemas/blob/feature/schemas.datapackages.org/definitions.json If we get sysadmin to setup the `schemas.datapackages.org` domain today I can merge it. It deals with the things in this PR.

**Comment by vitorbaptista** [comment]
@pwalsh Although we definitely need a way to avoid repetitions on the schemas, I wonder how these `$ref`s will work. If a schema has multiple `$ref`s to the same remote schema, does it download just once or multiple times? More importantly, what implications will it have on the local cache of https://github.com/okfn/datapackage-registry-py?

I wonder if there's some tool to "compile" the `$ref`s into the file, so we could write with `$ref`, but avoid making the user do multiple requests to get the full schema.

**Comment by pwalsh** [comment]
@vitorbaptista I'm not sure how it works in all libs that implement JSON Schema, but the python lib caches references, as per the docs on it.

**Comment by danfowler** [comment]
@pwalsh Great, I can close this PR, then.

**Pull request closed without merging**
